### ISSUE TITLE
MapView is giving FATAL Exception when it is inside CollapsingToolbarLayout

### ISSUE THREAD

**Issue by tayyabamin12** [TPLMaps/TPLMapsAndroidSdkSamples#2]
When using **MapView** inside the **CollapsingToolbarLayout**, it throws FATAL EXCEPTION ERROR when **interacting with any POI** rendered in maps, stack trace as image below: <br/>
![a](https://user-images.githubusercontent.com/22519934/64243037-18979080-cf20-11e9-8a23-f66a513eb87f.png)

**Comment by hassanjamil-magma** [comment]
I have already made a work around for the issue and fixed it in the `maps` module dependency version `1.3.11`, please incorporate
``` groovy
implementation 'com.tpl.maps.sdk:maps:1.3.1.1'
```

I hope you will not face it again.
> I recommended you to keep `MapView` as a parent UI component due to its extensive functionality (as a part of `Activity` or `Fragment`)
